# Generated by Django 3.0.6 on 2020-05-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('modal_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel.Destination')),
            ],
        ),
    ]
