# Generated by Django 3.0.6 on 2020-05-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0004_auto_20200511_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_images', models.ImageField(blank=True, upload_to='images/place_images')),
                ('place_description', models.TextField(blank=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='Travel.Destination')),
            ],
        ),
    ]
