# Generated by Django 3.0.6 on 2020-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_destdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destdescription',
            name='place_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
