# Generated by Django 3.0.6 on 2020-05-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0006_auto_20200527_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
